### ISSUE TITLE
Weird Problem about libLLVM

### ISSUE THREAD

**Issue by AndrewZhou7** [johnryantaylor/FDSE#1]
I have encountered a weird problem when running the program in Project 1. It says that FFMPEG is not installed properly and when I try to run '] build FFMPEG' it says unable to open libLLVM. I have tried to re-install Julia, but the problem remains. Some answers I found online suggests checking the LLVM version info, but I still couldn't see the problem. I have attached relevant information as txt.
[FFMPEG not installed properly.txt](https://github.com/johnryantaylor/FDSE/files/12129065/FFMPEG.not.installed.properly.txt)
[build FFMPEG.txt](https://github.com/johnryantaylor/FDSE/files/12129110/build.FFMPEG.txt)
[versioninfo.txt](https://github.com/johnryantaylor/FDSE/files/12129134/versioninfo.txt)

**Comment by mlin706** [comment]
run `@show Base.libllvm_path()` under the julia prompt to see if there's a dll file, then copy and rename that file to libLLVM.dll.

```
julia> @show Base.libllvm_path()
Base.libllvm_path() = Symbol("C:\\Users\\nookh\\AppData\\Local\\Programs\\Julia-1.9.2\\bin\\libLLVM-14jl.dll")
Symbol("C:\\Users\\nookh\\AppData\\Local\\Programs\\Julia-1.9.2\\bin\\libLLVM-14jl.dll")
```

from https://stackoverflow.com/questions/76001791/julia-julia-1-9-0-error-loaderror-unable-to-open-libllvm-when-llvm-is-insta

**Comment by AndrewZhou7** [comment]
That works, thanks a lot.
