### ISSUE TITLE
Problem running Project1 out of the box

### ISSUE THREAD

**Issue by janstenner** [johnryantaylor/FDSE#14]
Dear FDSE Team,

I am a researcher from Paderborn, Germany, currently investigating control schemes of Rayleigh Benard Convection systems.
Currently I'm using a python package called shenfun for the fluid dynamics simulation (https://shenfun.readthedocs.io/en/latest/rayleighbenard.html) but I want to see if I can use Oceananigans to have a julia-only solution and hopefully get a speed up aswell.

Now, after searching through the Oceananigans Discussions I stumbled upon a post by @johnryantaylor advertising this repository and I found that Project 1 seems really similar to the Rayleigh Benard problem stated in the link above (what is temperature in the Rayleigh Benard system looks exactly like buoyancy in Project 1 when looking at the equations).
Now, I am by no means a fluid dynamics expert so it is an open question to me if I can really just treat buoyancy like temperature and go with it.

However, I was confronted with problems when trying to run `gravitycurrent.jl`.

These functions are defined as 3 dimensional:
![grafik](https://github.com/user-attachments/assets/0533b9d2-d68d-48f3-8d0e-93722f703fe4)

The comments in the file and the readme also imply a 3D system but julia tries to access these functions with only two arguments:
![grafik](https://github.com/user-attachments/assets/02640660-ba50-4dff-80c7-c6ea0ed8aca1)

After inspection it looks to me (keep in mind that I am a newbie so I am not 100% sure) that the set up grid is in fact 2D:
![grafik](https://github.com/user-attachments/assets/b8620326-5eed-4175-9900-88fd345fc2da)

After manually defining 2D versions of said functions the whole `gravitycurrent.jl` ran through.
There was still another issue in `plot_gravitycurrent.jl` where I had to change `b_ic[:, 1, 1]` to `b_ic[:, 1, 1, 1]` in line 34 but that just looks like they changed the conventions of `FieldTimeSeries`.

Are/were you aware of this situation?
Is my fix right or did the error appear because I did something wrong?

Best
Jan

**Comment by johnryantaylor** [comment]
Hi @janstenner, thanks for the message.  This is due to a change in the Oceananigans interface.  When we wrote the projects the initial conditions always had to be 3D functions in Oceananigans, even when running 2D problems.  This has since changed.  I can update the scripts accordingly.  In the meantime, if you run activate and instantiate from the package manager inside the FDSE directory, the code should work as written since that will ensure that it uses the version of Oceananigans for which the code was written.

As a more general comment, 3D Rayleigh-Benard convection is definitely possible with Oceananigans, and if you have access to a GPU then you should see a significant speed-up.

**Comment by janstenner** [comment]
Thank you so much for the quick reply.

Yes, I did run the files in my own Project with the newest julia and Oceananigans versions available.
Your explanation makes total sense now.

3D Rayleigh Benard would be totally great - but that is a future thing for me. First I want to set up a 2D version and still wonder if the buoyancy b is as easily interchangable (or interpretable as) the temperature T. Do you by chance know something about that?

If not I will just experiment away and talk to some other people who can hopefully shed some light into that for me.

By the way thank you for the great project you have here!

**Comment by johnryantaylor** [comment]
When you non-dimensionalize the equations buoyancy and temperature and interchangeable.  Alternatively, you can use temperature in Oceananigans with a linear or nonlinear equation of state (you can even easily write your own equation of state).

**Comment by janstenner** [comment]
Thank you so much for confirming that!

Best wishes!
